version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs
hooks:
  BeforeInstall:
    - location: deploy_scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy_scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy_scripts/application_start.sh
      timeout: 300
      runas: ubuntu