import dashboard from './dashboard.service';

test('single fuel test', async () => {
  const params = {
    consumptions: [
      {
        id: 0,
        consumption: 99,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-01-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 65,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-02-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 79,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-03-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 75,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-04-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 87,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-05-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 81,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-06-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
    ],
    hdd: [
      { value: 43, date: new Date(2021, 0, 1), siteId: 1 },
      { value: 21, date: new Date(2021, 1, 1), siteId: 1 },
      { value: 25, date: new Date(2021, 2, 1), siteId: 1 },
      { value: 42, date: new Date(2021, 3, 1), siteId: 1 },
      { value: 57, date: new Date(2021, 4, 1), siteId: 1 },
      { value: 59, date: new Date(2021, 5, 1), siteId: 1 },
    ],
    nextConsumptions: [
      {
        id: 0,
        consumption: 99,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-01-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 40,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-02-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 70,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-03-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
    ],
    nextHdd: [
      { value: 14, date: new Date(2022, 0, 1), siteId: 1 },
      { value: 20, date: new Date(2022, 1, 1), siteId: 1 },
      { value: 25, date: new Date(2022, 2, 1), siteId: 1 },
    ],
  };

  const result = await dashboard.calculateWaste(params);
  expect(result[0].waste).toBe(-28.4652);
  expect(result[1].waste).toBe(32.846);
  expect(result[2].waste).toBe(4.7721);
});

test.only('lighting and power calculation', () => {
  const params = {
    baselineConsumptions: [
      {
        id: 0,
        consumption: 99,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-01-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 65,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-02-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 79,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-03-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 75,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-04-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 87,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-05-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 81,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-06-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 70,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-07-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 90,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-08-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 100,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-09-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 120,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-10-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 110,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-11-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 130,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-12-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
    ],

    projectedConsumptions: [
      {
        id: 0,
        consumption: 120,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-01-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 80,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-02-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 70,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-03-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 90,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-04-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 50,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-05-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 80,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-06-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 80,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-07-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 80,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-08-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 90,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-09-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 100,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-10-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 120,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-11-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
      {
        id: 0,
        consumption: 110,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-12-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: [1],
        siteId: 1,
      },
    ],
    baselineDaylight: 420,
    projectedDaylight: 400,
    baselinePopulation: 120,
    baselineTime: 130,
    projectedPopulation: 110,
    projectedTime: 150,
  };

   dashboard.wasteForPowerAndLighting(params);
});
