import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('activity history exposes older records through scoped pages and API', async ({ page, request }) => {
  const fixture = JSON.parse(await readFile('.local/e2e-report-schedules.json', 'utf8'));
  const path = `/org/${fixture.organisationId}/audit`;
  const api = `/api/v1/organisations/${fixture.organisationId}/audit`;
  expect((await request.get(`${api}/history`)).status()).toBe(401);
  expect((await request.get(`${api}/export`)).status()).toBe(401);
  await page.goto('/login');
  await page.getByLabel('Email address', { exact: true }).fill(fixture.email);
  await page.getByLabel('Password', { exact: true }).fill(fixture.password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/overview$/);
  await page.goto(path);
  await expect(page.getByRole('heading', { name: 'Recent activity' })).toBeVisible();
  await expect(page.locator('.audit-row')).toHaveCount(100);
  const response = await page.request.get(`${api}/history`);
  expect(response.headers()['cache-control']).toContain('no-store');
  const first = await response.json();
  expect(first.items).toHaveLength(100);
  await page.getByRole('link', { name: 'Older activity', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Earlier activity' })).toBeVisible();
  expect(new URL(page.url()).searchParams.get('cursor')).toBe(first.nextCursor);
  const second = await (await page.request.get(`${api}/history?cursor=${first.nextCursor}`)).json();
  expect(second.items.length).toBeGreaterThan(0);
  expect(
    second.items.some((item: { id: string }) => first.items.some((earlier: { id: string }) => earlier.id === item.id)),
  ).toBe(false);
  await page.getByRole('link', { name: 'Latest activity', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`${path}$`));
  expect(Array.isArray(await (await page.request.get(api)).json())).toBe(true);
  expect((await page.request.get(`${api}/history?cursor=invalid`)).status()).toBe(400);
  await page.getByLabel('Action code', { exact: true }).fill('test.audit_history');
  await page.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page.locator('.audit-row')).toHaveCount(100);
  const filtered = await (await page.request.get(`${api}/history?action=test.audit_history`)).json();
  expect(filtered.items.every((event: { action: string }) => event.action === 'test.audit_history')).toBe(true);
  await page.getByRole('link', { name: 'Older activity', exact: true }).click();
  await expect(page.locator('.audit-row')).toHaveCount(5);
  expect(new URL(page.url()).searchParams.get('action')).toBe('test.audit_history');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Export this page (JSON)', exact: true }).click();
  const downloaded = await downloadEvent;
  expect(downloaded.suggestedFilename()).toBe('activity-page.json');
  const exported = JSON.parse(await readFile((await downloaded.path())!, 'utf8'));
  expect(exported.items).toHaveLength(5);
  expect(exported.filters.action).toBe('test.audit_history');
  expect(exported.cursor).toBe(new URL(page.url()).searchParams.get('cursor'));
  expect(exported.nextCursor).toBeNull();
  const csv = await page.request.get(`${api}/export?format=csv&action=test.audit_history&cursor=${exported.cursor}`);
  expect(csv.headers()['content-type']).toContain('text/csv');
  expect(csv.headers()['cache-control']).toContain('no-store');
  expect(csv.headers()['x-content-type-options']).toBe('nosniff');
  expect(await csv.text()).toContain('"PAGE","audit-page-v1"');
  expect((await page.request.get(`${api}/export?format=html`)).status()).toBe(400);
  const receipts = await (await page.request.get(`${api}/history?action=audit.page_exported`)).json();
  expect(receipts.items.length).toBeGreaterThanOrEqual(2);
  await page.getByRole('link', { name: 'Latest activity', exact: true }).click();
  await expect(page.getByLabel('Action code', { exact: true })).toHaveValue('test.audit_history');
  await page.getByLabel('Request ID', { exact: true }).fill(filtered.items[0].correlationId);
  await page.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page.locator('.audit-row')).toHaveCount(1);
  expect(new URL(page.url()).searchParams.has('cursor')).toBe(false);
  await page.getByLabel('Action code', { exact: true }).fill('test.no_match');
  await page.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page.getByText('No activity matches these filters.')).toBeVisible();
  expect((await page.request.get(`${api}/history?action=one&action=two`)).status()).toBe(400);
  expect((await page.request.get(`${api}/history?requestId=invalid`)).status()).toBe(400);
  await page.getByRole('link', { name: 'Clear filters', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`${path}$`));
  await expect(page.getByLabel('Action code', { exact: true })).toHaveValue('');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
