import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('password signup and login work without email confirmation', async ({ page }, testInfo) => {
  const email = `password-${randomUUID()}@example.test`;
  const password = 'Browser password 123!';
  await page.goto('/login');
  await page.getByRole('link', { name: 'Create an account' }).click();
  await expect(page.getByRole('heading', { name: 'Create your account.' })).toBeVisible();
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await expect(page.getByLabel('Confirm password', { exact: true })).toHaveAttribute('required', '');
  await page.getByLabel('Confirm password', { exact: true }).fill('Different password 123!');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('main').getByRole('alert')).toContainText('Passwords do not match');
  expect((await page.request.get('/api/v1/organisations')).status()).toBe(401);
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByLabel('Confirm password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Create your organisation' })).toBeVisible();
  await page.getByLabel('Organisation name').fill('Password test workspace');
  await page.getByRole('button', { name: 'Create workspace' }).click();
  await expect(page).toHaveURL(/\/overview$/);
  const workspace = page.url();
  await page.reload();
  await expect(page).toHaveURL(workspace);
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await expect(page.getByLabel('Confirm password', { exact: true })).toHaveCount(0);
  expect((await page.request.get('/api/v1/organisations')).status()).toBe(401);
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Wrong password 123');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('main').getByRole('alert')).toContainText('Email or password is incorrect');
  await page.reload();
  await expect(page.getByRole('main').getByRole('alert')).toHaveCount(0);
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(workspace);
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.goto('/signup');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: testInfo.outputPath('signup-mobile.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('Replacement password 123');
  await page.getByLabel('Confirm password', { exact: true }).fill('Replacement password 123');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('main').getByRole('alert')).toContainText('Unable to create this account');
});
