import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('Businesses').insert([
    {
      id: 198,
      businessName: 'long name',
      businessType: 'a type',
      businessService: 'a service',
      password: '$2b$10$XYSGA3eqhW17sX1Gyb83bemjRva.O2CfzlgE6EJH.NGBnKlyuWQWW', // 123456Abc!
      siteName: 'a site',
      buildingName: 'a name',
      contactName: 'a contact name',
      position: 'a position',
      phoneNumber: '+55 122334444',
      email: 'mail198@mail.com',
      countryId: 2,
      stateId: 42,
      town: 'a town',
      currencyCode: 'USD',
      postCode: '485 s8d',
      subscriptionDate: new Date().toISOString().split('T')[0],
    },
    {
      id: 212,
      businessName: 'long name',
      businessType: 'a type',
      businessService: 'a service',
      password: '$2b$10$XYSGA3eqhW17sX1Gyb83bemjRva.O2CfzlgE6EJH.NGBnKlyuWQWW', // 123456Abc!
      siteName: 'a site',
      buildingName: 'a name',
      contactName: 'a contact name',
      position: 'a position',
      phoneNumber: '+55 122334444',
      email: 'mail212@mail.com',
      countryId: 2,
      stateId: 42,
      town: 'a town',
      currencyCode: 'USD',
      postCode: '485 s8d',
      subscriptionDate: new Date().toISOString().split('T')[0],
    },
    {
      id: 218,
      businessName: 'long name',
      businessType: 'a type',
      businessService: 'a service',
      password: '$2b$10$XYSGA3eqhW17sX1Gyb83bemjRva.O2CfzlgE6EJH.NGBnKlyuWQWW', // 123456Abc!
      siteName: 'a site',
      buildingName: 'a name',
      contactName: 'a contact name',
      position: 'a position',
      phoneNumber: '+55 122334444',
      email: 'mail218@mail.com',
      countryId: 2,
      stateId: 42,
      town: 'a town',
      currencyCode: 'USD',
      postCode: '485 s8d',
      subscriptionDate: new Date().toISOString().split('T')[0],
    },

    {
      id: 302,
      businessName: 'long name',
      businessType: 'a type',
      businessService: 'a service',
      password: '$2b$10$XYSGA3eqhW17sX1Gyb83bemjRva.O2CfzlgE6EJH.NGBnKlyuWQWW', // 123456Abc!
      siteName: 'a site',
      buildingName: 'a name',
      contactName: 'a contact name',
      position: 'a position',
      phoneNumber: '+55 122334444',
      email: 'userdashboard302@mail.com',
      countryId: 2,
      stateId: 42,
      town: 'a town',
      currencyCode: 'USD',
      postCode: '02532',
      subscriptionDate: new Date().toISOString().split('T')[0],
    },

    {
      id: 222,
      businessName: 'long name',
      businessType: 'a type',
      businessService: 'a service',
      password: '$2b$10$XYSGA3eqhW17sX1Gyb83bemjRva.O2CfzlgE6EJH.NGBnKlyuWQWW', // 123456Abc!
      siteName: 'a site',
      buildingName: 'a name',
      contactName: 'a contact name',
      position: 'a position',
      phoneNumber: '+55 122334444',
      email: 'userdashboard1@mail.com',
      countryId: 2,
      stateId: 42,
      town: 'a town',
      currencyCode: 'USD',
      postCode: '485 s8d',
      subscriptionDate: new Date().toISOString().split('T')[0],
    },
  ]);

  await knex('Sites').insert([
    {
      id: 441,
      type: 'some',
      address: 'anywhere',
      postCode: '484 sd8',
      town: 'some town',
      population: 15000,
      workinghours: 2,
      fullTimeEmployee: false,
      size: 15,
      businessId: 198,
    },
    {
      id: 448,
      type: 'some',
      address: 'anywhere',
      postCode: '484 sd8',
      town: 'some town',
      population: 15000,
      fullTimeEmployee: false,
      workinghours: 2,
      size: 15,
      businessId: 212,
    },
    {
      id: 450,
      type: 'some',
      address: 'anywhere',
      postCode: '484 sd8',
      town: 'some town',
      population: 15000,
      fullTimeEmployee: false,
      workinghours: 2,
      size: 15,
      businessId: 222,
    },
    {
      id: 451,
      type: 'some',
      address: 'anywhere',
      postCode: '484 sd8',
      town: 'some town',
      population: 15000,
      fullTimeEmployee: false,
      workinghours: 2,
      size: 15,
      businessId: 302,
    },
  ]);

  await knex('Utilities').insert([
    {
      id: 498,
      name: 'Heat',
      businessId: 198,
    },
    {
      id: 124,
      name: 'Gas',
      businessId: 212,
    },
    {
      id: 184,
      name: 'Gas 2',
      businessId: 218,
    },
    {
      id: 186,
      name: 'Gas 3',
      businessId: 222,
    },
  ]);

  await knex('UtilityConsumptions').insert([
    {
      id: 22,
      date: '2020-01-01',
      consumption: 100,
      cost: 100,
      fuelSourceId: 1,
      siteId: 451,
    },
    {
      id: 24,
      date: '2020-02-01',
      consumption: 150,
      cost: 200,
      fuelSourceId: 1,
      siteId: 451,
    },
    {
      id: 26,
      date: '2020-03-01',
      consumption: 150,
      cost: 200,
      fuelSourceId: 1,
      siteId: 451,
    },
  ]);
}
