import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('Businesses').insert([
    {
      id: 324,
      businessName: 'long name',
      businessType: 'a type',
      businessService: 'a service',
      password: '$2b$10$XYSGA3eqhW17sX1Gyb83bemjRva.O2CfzlgE6EJH.NGBnKlyuWQWW', // 123456Abc!
      siteName: 'a site',
      buildingName: 'a name',
      contactName: 'a contact name',
      position: 'a position',
      phoneNumber: '+55 122334444',
      email: 'mail324@mail.com',
      countryId: 2,
      stateId: 42,
      town: 'a town',
      postCode: '02532',
      subscriptionDate: new Date().toISOString().split('T')[0],
      holydayDate: new Date().toISOString().split('T')[0],
      totalArea: 200,
      totalPopulation: 5122,
    },
  ]);

  const site = {
    id: 488,
    type: 'some',
    address: 'site 2',
    postCode: '486 sd8',
    town: 'some town',
    population: 15000,
    size: 15,
    businessId: 324,
  };

  await knex('Sites').insert([site]);

  await knex('UtilityConsumptions').insert([
    {
      date: '2019-01-01',
      consumption: 157,
      cost: 99 * 3,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-02-01',
      consumption: 65,
      cost: 65 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-03-01',
      consumption: 79,
      cost: 79 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-04-01',
      consumption: 75,
      cost: 75 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-05-01',
      consumption: 87,
      cost: 87 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-06-01',
      consumption: 81,
      cost: 81 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-07-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-08-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-09-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-10-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-11-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-12-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    //2020
    {
      date: '2020-01-01',
      consumption: 99,
      cost: 99 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-01-01',
      consumption: 99,
      cost: 99 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2020-02-01',
      consumption: 40,
      cost: 40 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-03-01',
      consumption: 70,
      cost: 70 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    /*{
      date: '2020-04-01',
      consumption: 46,
      cost: 46 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-05-01',
      consumption: 67,
      cost: 67 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-06-01',
      consumption: 16,
      cost: 16 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-07-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-08-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-09-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-10-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-11-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-12-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },*/
    //2021
    {
      date: '2021-01-01',
      consumption: 37,
      cost: 37 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-02-01',
      consumption: 64,
      cost: 64 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-03-01',
      consumption: 44,
      cost: 44 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-04-01',
      consumption: 78,
      cost: 78 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-05-01',
      consumption: 55,
      cost: 55 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-06-01',
      consumption: 19,
      cost: 19 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-07-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-08-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-09-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-10-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-11-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-12-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    //2022
    {
      date: '2022-01-01',
      consumption: 39,
      cost: 39 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2022-02-01',
      consumption: 11,
      cost: 11 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },

    {
      date: '2016-01-01',
      consumption: 11,
      cost: 11 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2016-02-01',
      consumption: 34,
      cost: 34 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2016-04-01',
      consumption: 44,
      cost: 44 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },

    {
      date: '2015-01-01',
      consumption: 11,
      cost: 11 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2015-02-01',
      consumption: 34,
      cost: 34 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2015-05-01',
      consumption: 34,
      cost: 34 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
  ]);

  await knex('UtilityEmissions').insert([
    {
      year: 2020,
      value: 200,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      year: 2019,
      value: 200,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      year: 2020,
      value: 220,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      year: 2019,
      value: 250,
      fuelSourceId: 2,
      siteId: site.id,
    },
  ]);
}
