import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('Businesses').insert([
    {
      id: 324,
      businessName: 'long name',
      businessType: 'a type',
      businessService: 'a service',
      password: '$2b$10$XYSGA3eqhW17sX1Gyb83bemjRva.O2CfzlgE6EJH.NGBnKlyuWQWW', // 123456Abc!
      siteName: 'a site',
      buildingName: 'a name',
      contactName: 'a contact name',
      position: 'a position',
      phoneNumber: '+55 122334444',
      email: 'mail324@mail.com',
      countryId: 2,
      stateId: 42,
      town: 'a town',
      postCode: '02532',
      subscriptionDate: new Date().toISOString().split('T')[0],
      holydayDate: new Date().toISOString().split('T')[0],
      totalArea: 200,
      totalPopulation: 5122,
    },
  ]);

  const site = {
    id: 488,
    type: 'some',
    address: 'site 1',
    postCode: '486 sd8',
    town: 'some town',
    population: 15000,
    size: 15,
    businessId: 324,
  };

  const site2 = {
    id: 490,
    type: 'some',
    address: 'site 2',
    postCode: '486 sd8',
    town: 'some town',
    population: 15000,
    size: 15,
    businessId: 324,
  };

  await knex('Sites').insert([
    site,
    site2,
    {
      id: 493,
      type: 'some',
      address: 'site 3',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 494,
      type: 'some',
      address: 'site 4',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 495,
      type: 'some',
      address: 'site 5',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 496,
      type: 'some',
      address: 'site 6',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 497,
      type: 'some',
      address: 'site 7',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 498,
      type: 'some',
      address: 'site 8',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 499,
      type: 'some',
      address: 'site 9',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 500,
      type: 'some',
      address: 'site 10',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 501,
      type: 'some',
      address: 'site 11',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 502,
      type: 'some',
      address: 'site 12',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 503,
      type: 'some',
      address: 'site 13',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 504,
      type: 'some',
      address: 'site 14',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 505,
      type: 'some',
      address: 'site 15',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 506,
      type: 'some',
      address: 'site 16',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 507,
      type: 'some',
      address: 'site 17',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 508,
      type: 'some',
      address: 'site 18',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 509,
      type: 'some',
      address: 'site 19',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 510,
      type: 'some',
      address: 'site 20',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 511,
      type: 'some',
      address: 'site 21',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
    {
      id: 512,
      type: 'some',
      address: 'site 22',
      postCode: '486 sd8',
      town: 'some town',
      population: 15000,
      size: 15,
      businessId: 324,
    },
  ]);

  await knex('UtilityConsumptions').insert([
    {
      date: '2019-01-01',
      consumption: 157,
      cost: 99 * 3,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-02-01',
      consumption: 65,
      cost: 65 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-03-01',
      consumption: 985,
      cost: 65 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },

    {
      date: '2019-01-01',
      consumption: 345,
      cost: 99 * 3,
      fuelSourceId: 1,
      siteId: site2.id,
    },
    {
      date: '2019-02-01',
      consumption: 485,
      cost: 65 * 2,
      fuelSourceId: 1,
      siteId: site2.id,
    },
    {
      date: '2019-03-01',
      consumption: 198,
      cost: 65 * 2,
      fuelSourceId: 1,
      siteId: site2.id,
    },

    {
      date: '2019-03-01',
      consumption: 79,
      cost: 79 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-04-01',
      consumption: 75,
      cost: 75 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-05-01',
      consumption: 87,
      cost: 87 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-06-01',
      consumption: 81,
      cost: 81 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-07-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-08-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-09-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-10-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-11-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2019-12-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    //2020
    {
      date: '2020-01-01',
      consumption: 99,
      cost: 99 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-01-01',
      consumption: 99,
      cost: 99 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2020-02-01',
      consumption: 40,
      cost: 40 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-03-01',
      consumption: 70,
      cost: 70 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-04-01',
      consumption: 198,
      cost: 70 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2020-04-01',
      consumption: 87,
      cost: 70 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2020-04-01',
      consumption: 34,
      cost: 70 * 2,
      fuelSourceId: 3,
      siteId: site.id,
    },
    {
      date: '2020-04-01',
      consumption: 250,
      cost: 70 * 2,
      fuelSourceId: 4,
      siteId: site.id,
    },
    {
      date: '2020-04-01',
      consumption: 112,
      cost: 70 * 2,
      fuelSourceId: 5,
      siteId: site.id,
    },
    {
      date: '2020-05-01',
      consumption: 648,
      cost: 70 * 2,
      fuelSourceId: 5,
      siteId: site.id,
    },
    {
      date: '2020-06-01',
      consumption: 432,
      cost: 70 * 2,
      fuelSourceId: 5,
      siteId: site.id,
    },
    //site2
    {
      date: '2020-01-01',
      consumption: 99,
      cost: 99 * 2,
      fuelSourceId: 2,
      siteId: site2.id,
    },
    {
      date: '2020-01-01',
      consumption: 40,
      cost: 40 * 2,
      fuelSourceId: 1,
      siteId: site2.id,
    },
    {
      date: '2020-02-01',
      consumption: 40,
      cost: 40 * 2,
      fuelSourceId: 1,
      siteId: site2.id,
    },

    {
      date: '2020-01-01',
      consumption: 99,
      cost: 99 * 2,
      fuelSourceId: 3,
      siteId: site2.id,
    },
    {
      date: '2020-02-01',
      consumption: 40,
      cost: 40 * 2,
      fuelSourceId: 3,
      siteId: site2.id,
    },
    //2021
    {
      date: '2021-01-01',
      consumption: 37,
      cost: 37 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-02-01',
      consumption: 64,
      cost: 64 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-03-01',
      consumption: 44,
      cost: 44 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-04-01',
      consumption: 78,
      cost: 78 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-05-01',
      consumption: 55,
      cost: 55 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-06-01',
      consumption: 19,
      cost: 19 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-07-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-08-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-09-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-10-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-11-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2021-12-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    //2022
    {
      date: '2022-01-01',
      consumption: 39,
      cost: 39 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      date: '2022-02-01',
      consumption: 11,
      cost: 11 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },

    {
      date: '2016-01-01',
      consumption: 11,
      cost: 11 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2016-02-01',
      consumption: 34,
      cost: 34 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2016-04-01',
      consumption: 44,
      cost: 44 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },

    {
      date: '2015-01-01',
      consumption: 11,
      cost: 11 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2015-02-01',
      consumption: 34,
      cost: 34 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
    {
      date: '2015-05-01',
      consumption: 34,
      cost: 34 * 2,
      fuelSourceId: 2,
      siteId: site.id,
    },
  ]);

  await knex('UtilityEmissions').insert([
    {
      year: 2020,
      value: 200,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      year: 2019,
      value: 200,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      year: 2020,
      value: 220,
      fuelSourceId: 2,
      siteId: site.id,
    },

    //site2
    {
      year: 2019,
      value: 200,
      fuelSourceId: 1,
      siteId: site2.id,
    },
    {
      year: 2020,
      value: 220,
      fuelSourceId: 1,
      siteId: site2.id,
    },

    {
      year: 2020,
      value: 220,
      fuelSourceId: 3,
      siteId: site.id,
    },
    {
      year: 2020,
      value: 220,
      fuelSourceId: 4,
      siteId: site.id,
    },
    {
      year: 2020,
      value: 220,
      fuelSourceId: 5,
      siteId: site.id,
    },
    {
      year: 2019,
      value: 250,
      fuelSourceId: 2,
      siteId: site.id,
    },
  ]);
  await knex('BusinessLog').insert([
    {
      id: 102,
      startDate: '2020-10-01',
      endDate: '2020-10-08',
      comments: 'some long comment',
      operation: 'some operation',
      siteId: site.id,
      usedInId: 2,
    },
  ]);

  await knex('BusinessTenant').insert([
    {
      id: 104,
      date: '2021-10-09',
      regularTenantAmount: 25,
      irregularTenantAmount: 25,
      siteId: site.id,
      usedInId: 2,
    },
    {
      id: 106,
      date: '2020-10-01',
      regularTenantAmount: 25,
      irregularTenantAmount: 55,
      siteId: site.id,
      usedInId: 3,
    },
  ]);
}
