import { Knex } from 'knex';
import { buildFakeBusiness, buildFakeConsumption, buildFakeSite } from '../../test/testhelp';

export async function seed(knex: Knex): Promise<void> {
  await knex('Businesses').insert([buildFakeBusiness({ id: 322, email: 'mail322@mail.com' })]);

  const site = {
    id: 484,
    businessId: 322,
  };
  const site2 = {
    id: 486,
    businessId: 322,
  };
  await knex('Sites').insert([
    buildFakeSite({ id: site.id, businessId: site.businessId, name: 'Site 484' }),
    buildFakeSite({ id: site2.id, businessId: site2.businessId }),
  ]);

  await knex('UtilityConsumptions').insert([
    buildFakeConsumption({
      id: 3100,
      date: '2019-01-01',
      consumption: 99,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3102,
      date: '2019-02-01',
      consumption: 65,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3104,
      date: '2019-03-01',
      consumption: 79,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3106,
      date: '2019-04-01',
      consumption: 75,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3108,
      date: '2019-05-01',
      consumption: 87,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3110,
      date: '2019-06-01',
      consumption: 81,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3112,
      date: '2019-07-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3114,
      date: '2019-08-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3116,
      date: '2019-09-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3118,
      date: '2019-10-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3120,
      date: '2019-11-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3122,
      date: '2019-12-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    //2020
    buildFakeConsumption({
      id: 3124,
      date: '2020-01-01',
      consumption: 99,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3126,
      date: '2020-02-01',
      consumption: 89,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3128,
      date: '2020-03-01',
      consumption: 27,
      fuelSourceId: 1,
      siteId: site.id,
    }),

    buildFakeConsumption({
      id: 3123,
      date: '2020-01-01',
      consumption: 18,
      fuelSourceId: 2,
      siteId: site.id,
    }),

    buildFakeConsumption({
      id: 3130,
      date: '2020-03-01',
      consumption: 37,
      fuelSourceId: 1,
      siteId: site2.id,
    }),

    buildFakeConsumption({
      id: 3132,
      date: '2020-03-01',
      consumption: 46,
      fuelSourceId: 2,
      siteId: site2.id,
    }),
    /*{
      id: 3130,
      date: '2020-04-01',
      consumption: 46,
      cost: 46 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      id: 3132,
      date: '2020-05-01',
      consumption: 67,
      cost: 67 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      id: 3134,
      date: '2020-06-01',
      consumption: 16,
      cost: 16 * 2,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      id: 3136,
      date: '2020-07-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      id: 3138,
      date: '2020-08-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      id: 140,
      date: '2020-09-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      id: 3142,
      date: '2020-10-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      id: 3144,
      date: '2020-11-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },
    {
      id: 3146,
      date: '2020-12-01',
      consumption: 0,
      cost: 0,
      fuelSourceId: 1,
      siteId: site.id,
    },*/
    //2021
    buildFakeConsumption({
      id: 3148,
      date: '2021-01-01',
      consumption: 37,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3150,
      date: '2021-02-01',
      consumption: 64,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3152,
      date: '2021-03-01',
      consumption: 44,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3154,
      date: '2021-04-01',
      consumption: 78,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3156,
      date: '2021-05-01',
      consumption: 55,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3158,
      date: '2021-06-01',
      consumption: 19,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3160,
      date: '2021-07-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3162,
      date: '2021-08-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3164,
      date: '2021-09-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3166,
      date: '2021-10-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3168,
      date: '2021-11-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3170,
      date: '2021-12-01',
      consumption: 0,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    //2022
    buildFakeConsumption({
      id: 3172,
      date: '2022-01-01',
      consumption: 39,
      fuelSourceId: 1,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3174,
      date: '2022-02-01',
      consumption: 11,
      fuelSourceId: 1,
      siteId: site.id,
    }),

    buildFakeConsumption({
      id: 3176,
      date: '2016-01-01',
      consumption: 11,
      fuelSourceId: 2,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3178,
      date: '2016-02-01',
      consumption: 34,
      fuelSourceId: 2,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3179,
      date: '2016-04-01',
      consumption: 44,
      fuelSourceId: 2,
      siteId: site.id,
    }),

    buildFakeConsumption({
      id: 3180,
      date: '2015-01-01',
      consumption: 11,
      fuelSourceId: 2,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3182,
      date: '2015-02-01',
      consumption: 34,
      fuelSourceId: 2,
      siteId: site.id,
    }),
    buildFakeConsumption({
      id: 3184,
      date: '2015-05-01',
      consumption: 34,
      fuelSourceId: 2,
      siteId: site.id,
    }),
  ]);
}
