/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["Register"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Register"];
    };
  };
  "/api/auth/login": {
    /** Return JWT token. */
    post: {
      responses: {
        200: components["responses"]["Login"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Login"];
    };
  };
  "/api/site/": {
    /** Create a new site for a business. */
    post: {
      responses: {
        200: components["responses"]["Site"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Site"];
    };
  };
  "/api/utility/savingTips": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetSavingTips"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/fuelSources": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetFuelSources"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/emissions": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetEmissions"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/consumptions": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetConsumptions"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/addEmission/{fuelSourceId}": {
    /** Add emision to utility. */
    post: {
      parameters: {
        path: {
          fuelSourceId: string;
        };
      };
      responses: {
        200: components["responses"]["AddFuelSourceEmission"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["AddFuelSourceEmission"];
    };
  };
  "/api/utility/addConsumption/{fuelSourceId}": {
    /** Add emision to utility. */
    post: {
      parameters: {
        path: {
          fuelSourceId: string;
        };
      };
      responses: {
        200: components["responses"]["AddFuelSourceConsumption"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["AddFuelSourceConsumption"];
    };
  };
  "/api/utility/importUtility": {
    /** Import excel file. */
    post: {
      responses: {
        200: components["responses"]["UtilityFileImport"];
        400: components["schemas"]["GenericError"];
      };
      requestBody: components["requestBodies"]["UtilityFileImport"];
    };
  };
  "/api/dashboard/": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetDashboardData"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetUser"];
        400: components["responses"]["GenericError"];
      };
    };
    /** Create a new user. */
    put: {
      responses: {
        200: components["responses"]["UpdateUser"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["UpdateUser"];
    };
  };
  "/api/business/energies": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetBusinessEnergy"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/sites": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetSites"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/foors": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetFloors"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/saveEnergy": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SaveBusinessEnergy"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/addLog": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["AddLog"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/setTenants": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetTenants"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/setFloors": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetFloors"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SetFloors"];
    };
  };
  "/api/business/setReviews": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetReviews"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/setProgrammes": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetProgrammes"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
}

export interface components {
  schemas: {
    GenericError: {
      statusCode: number;
      message: string;
    };
    SuccessMessage: {
      success: boolean;
    };
    Site: {
      type: string;
      address: string;
      postCode: string;
      town: string;
      population: number;
      size: number;
    };
    JWTToken: {
      jwt: string;
    };
    BusinessPattern: {
      startDate: string;
      endDate: string;
      consumption: number;
      daysOnYear: number;
      siteId: number;
      usedInId: number;
    };
    Programme: {
      question: string;
      siteId: number;
      usedInId: number;
      answers: string[];
    };
    Review: {
      question: string;
      siteId: number;
      answers: string[];
    };
    BusinessBrand: {
      name: string;
      rate: number;
      startTime: string;
      endTime: string;
      days: string[];
    };
    BusinessCost: {
      currencyCode: string;
      vat: number;
    };
    BusinessDistance: {
      meters: string;
    };
    BusinessFloor: {
      size: string;
      area: number;
      population: number;
    };
    SavingTip: {
      id: number;
      category: string;
      text: string;
      imageUrl?: string | null;
    };
    BusinessEnergy: {
      siteId: number;
      records: {
        fuelSourceId: number;
        brands: components["schemas"]["BusinessBrand"][];
        meternumbers: components["schemas"]["BusinessDistance"][];
        cost: components["schemas"]["BusinessCost"];
      }[];
    };
    Tenant: {
      siteId: number;
      usedInId: number;
      date: string;
      regularTenantAmount: number;
      irregularTenantAmount: number;
    };
    FuelSource: {
      source: string;
      usedIn: string[];
    };
    RegisterBody: {
      businessName: string;
      businessType: string;
      businessService: string;
      password: string;
      siteName: string;
      buildingName: string;
      contactName: string;
      position: string;
      phoneNumber: string;
      email: string;
      country: string;
      state: string;
      town: string;
      postCode: string;
      subscriptionDate: string;
      holydayDate: string;
      totalArea: number;
      totalPopulation: number;
    };
    User: components["schemas"]["RegisterBody"] & {
      id: number;
      floors?: {
        size: string;
        area: number;
        population: number;
      }[];
      patterns?: components["schemas"]["BusinessPattern"][];
    };
    AddFuelSourceConsumptionBody: {
      date: string;
      consumption: number;
      cost: number;
    };
    UtilityConsumption: components["schemas"]["AddFuelSourceConsumptionBody"] & {
      id: number;
    };
    AddFuelSourceEmissionBody: {
      emissionFactor: string;
      value: number;
      year: number;
    };
    UtilityEmission: components["schemas"]["AddFuelSourceEmissionBody"] & {
      id: number;
    };
  };
  responses: {
    /** Error message */
    GenericError: {
      content: {
        "application/json": components["schemas"]["GenericError"];
      };
    };
    /** Success message */
    Register: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    Login: {
      content: {
        "application/json": components["schemas"]["JWTToken"];
      };
    };
    /** Success message */
    Site: {
      content: {
        "application/json": {
          id: number;
        };
      };
    };
    /** Success message */
    AddFuelSourceConsumption: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    UtilityFileImport: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetDashboardData: {
      content: {
        "application/json": {
          date: string;
          averageConsumption: number;
          averageCost: number;
          consumption: number;
        }[];
      };
    };
    /** Success message */
    UpdateUser: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetUser: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    /** Success message */
    SaveBusinessEnergy: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetSavingTips: {
      content: {
        "application/json": components["schemas"]["SavingTip"][];
      };
    };
    /** Success message */
    GetBusinessEnergy: {
      content: {
        "application/json": components["schemas"]["BusinessEnergy"][];
      };
    };
    /** Success message */
    AddFuelSourceEmission: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    AddLog: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    SetTenants: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    SetReviews: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    SetProgrammes: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetSites: {
      content: {
        "application/json": (components["schemas"]["Site"] & {
          id: number;
        })[];
      };
    };
    /** Success message */
    GetFuelSources: {
      content: {
        "application/json": (components["schemas"]["FuelSource"] & {
          id: number;
        })[];
      };
    };
    /** Success message */
    SetFloors: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetFloors: {
      content: {
        "application/json": components["schemas"]["BusinessFloor"][];
      };
    };
    /** Success message */
    GetEmissions: {
      content: {
        "application/json": components["schemas"]["UtilityEmission"][];
      };
    };
    /** Success message */
    GetConsumptions: {
      content: {
        "application/json": components["schemas"]["UtilityConsumption"][];
      };
    };
  };
  parameters: {
    AddFuelSourceConsumption: number;
    AddFuelSourceEmission: number;
  };
  requestBodies: {
    Register: {
      content: {
        "application/json": components["schemas"]["RegisterBody"];
      };
    };
    Login: {
      content: {
        "application/json": {
          email: string;
          password: string;
        };
      };
    };
    Site: {
      content: {
        "application/json": components["schemas"]["Site"];
      };
    };
    AddFuelSourceConsumption: {
      content: {
        "application/json": components["schemas"]["AddFuelSourceConsumptionBody"];
      };
    };
    UtilityFileImport: {
      content: {
        "multipart/form-data": {
          excel?: string;
        };
        "application/json": string;
      };
    };
    UpdateUser: {
      content: {
        "application/json": components["schemas"]["RegisterBody"];
      };
    };
    SaveBusinessEnergy: {
      content: {
        "application/json": components["schemas"]["BusinessEnergy"];
      };
    };
    AddFuelSourceEmission: {
      content: {
        "application/json": components["schemas"]["AddFuelSourceEmissionBody"][];
      };
    };
    AddLog: {
      content: {
        "application/json": {
          siteId: number;
          usedInId: number;
          operation: string;
          comments: string;
          startDate: string;
          endDate: string;
        };
      };
    };
    SetTenants: {
      content: {
        "application/json": components["schemas"]["Tenant"][];
      };
    };
    SetReviews: {
      content: {
        "application/json": components["schemas"]["Review"][];
      };
    };
    SetProgrammes: {
      content: {
        "application/json": components["schemas"]["Programme"][];
      };
    };
    SetFloors: {
      content: {
        "application/json": components["schemas"]["BusinessFloor"][];
      };
    };
  };
}

export interface operations {}

export interface external {}
