/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["Register"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Register"];
    };
  };
  "/api/auth/login": {
    /** Return JWT token. */
    post: {
      responses: {
        200: components["responses"]["Login"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Login"];
    };
  };
  "/api/site/": {
    /** Create a new site for a business. */
    post: {
      responses: {
        200: components["responses"]["Site"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Site"];
    };
  };
  "/api/utility/": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetUtilities"];
        400: components["responses"]["GenericError"];
      };
    };
    /** Create a new utility. */
    post: {
      responses: {
        200: components["responses"]["CreateUtility"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["CreateUtility"];
    };
  };
  "/api/utility/addEmission/{utilityId}": {
    /** Add emision to utility. */
    post: {
      parameters: {
        path: {
          utilityId: string;
        };
      };
      responses: {
        200: components["responses"]["AddUtilityEmission"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["CreateUtility"];
    };
  };
  "/api/utility/importUtility": {
    /** Import excel file. */
    post: {
      responses: {
        200: components["responses"]["UtilityFileImport"];
        400: components["schemas"]["GenericError"];
      };
      requestBody: components["requestBodies"]["UtilityFileImport"];
    };
  };
  "/api/utility/savingTips": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetSavingTips"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/dashboard/": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetDashboardData"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetUser"];
        400: components["responses"]["GenericError"];
      };
    };
    /** Create a new user. */
    put: {
      responses: {
        200: components["responses"]["UpdateUser"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["UpdateUser"];
    };
  };
  "/api/business/setBrands": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetBrands"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SetBrands"];
    };
  };
}

export interface components {
  schemas: {
    GenericError: {
      statusCode: number;
      message: string;
    };
    SuccessMessage: {
      success: boolean;
    };
    SiteRequestBody: {
      type: string;
      address: string;
      postCode: string;
      town: number;
      population: number;
      size: number;
      fuel: string;
      uses: string;
    };
    Site: components["schemas"]["SiteRequestBody"] & {
      id: number;
      businessId: string;
    };
    JWTToken: {
      jwt: string;
    };
    BusinessService: {
      startDate: string;
      endDate: string;
      consumption: number;
      daysOnYear: number;
    };
    Programme: {
      question: string;
      utilityId: number;
      answers: string[];
    };
    Brand: {
      name: string;
      rate: number;
      startTime: string;
      endTime: string;
      days: string[];
    };
    SavingTip: {
      id: number;
      category: string;
      text: string;
      imageUrl?: string | null;
    };
    RegisterBody: {
      businessName: string;
      businessType: string;
      businessService: string;
      password: string;
      siteName: string;
      buildingName: string;
      contactName: string;
      position: string;
      phoneNumber: string;
      email: string;
      country: string;
      state: string;
      town: string;
      postCode: string;
      subscriptionDate: string;
      holydayDate: string;
      totalArea: number;
      totalPopulation: number;
      floors: {
        size: string;
        area: number;
        population: number;
      }[];
      cooling?: components["schemas"]["BusinessService"];
      heating?: components["schemas"]["BusinessService"];
      lighting?: components["schemas"]["BusinessService"];
      powering?: components["schemas"]["BusinessService"];
      programmes?: components["schemas"]["Programme"][];
    };
    User: components["schemas"]["RegisterBody"] & {
      id: number;
    };
    Utility: {
      id: number;
      name: string;
    };
    AddUtilityEmissionBody: {
      date: string;
      consumption: number;
      cost: number;
    };
    UtilityConsumption: components["schemas"]["AddUtilityEmissionBody"] & {
      id: number;
    };
  };
  responses: {
    /** Error message */
    GenericError: {
      content: {
        "application/json": components["schemas"]["GenericError"];
      };
    };
    /** Success message */
    Register: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    Login: {
      content: {
        "application/json": components["schemas"]["JWTToken"];
      };
    };
    /** Success message */
    Site: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    CreateUtility: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    AddUtilityEmission: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    UtilityFileImport: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetDashboardData: {
      content: {
        "application/json": {
          date: string;
          averageConsumption: number;
          averageCost: number;
          consumption: number;
        }[];
      };
    };
    /** Success message */
    GetUtilities: {
      content: {
        "application/json": components["schemas"]["Utility"][];
      };
    };
    /** Success message */
    UpdateUser: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetUser: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    /** Success message */
    SetBrands: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetSavingTips: {
      content: {
        "application/json": components["schemas"]["SavingTip"][];
      };
    };
  };
  parameters: {
    AddUtilityEmission: number;
  };
  requestBodies: {
    Register: {
      content: {
        "application/json": components["schemas"]["RegisterBody"];
      };
    };
    Login: {
      content: {
        "application/json": {
          email: string;
          password: string;
        };
      };
    };
    Site: {
      content: {
        "application/json": components["schemas"]["SiteRequestBody"];
      };
    };
    CreateUtility: {
      content: {
        "application/json": {
          name: string;
        };
      };
    };
    AddUtilityEmission: {
      content: {
        "application/json": components["schemas"]["AddUtilityEmissionBody"];
      };
    };
    UtilityFileImport: {
      content: {
        "multipart/form-data": {
          excel?: string;
        };
        "application/json": string;
      };
    };
    UpdateUser: {
      content: {
        "application/json": components["schemas"]["RegisterBody"];
      };
    };
    SetBrands: {
      content: {
        "application/json": {
          brands: components["schemas"]["Brand"][];
        };
      };
    };
  };
}

export interface operations {}

export interface external {}
