/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["Register"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Register"];
    };
  };
  "/api/auth/login": {
    /** Return JWT token. */
    post: {
      responses: {
        200: components["responses"]["Login"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Login"];
    };
  };
  "/api/site/details/{siteId}": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        path: {
          siteId: string;
        };
      };
      responses: {
        200: components["responses"]["GetSiteDetails"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/site/countries": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetCountries"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/site/states": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          countryId?: string;
        };
      };
      responses: {
        200: components["responses"]["GetStates"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/site/": {
    /** Create a new site for a business. */
    post: {
      responses: {
        200: components["responses"]["Site"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["Site"];
    };
    /** Create a new site for a business. */
    delete: {
      responses: {
        200: components["responses"]["DeleteSite"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["DeleteSite"];
    };
  };
  "/api/site/setConversionUnit/{siteId}": {
    /** Create a new site for a business. */
    post: {
      parameters: {
        path: {
          siteId: string;
        };
      };
      responses: {
        200: components["responses"]["SetSiteConversionUnit"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SetSiteConversionUnit"];
    };
  };
  "/api/site/update/{siteId}": {
    /** Create a new site for a business. */
    put: {
      parameters: {
        path: {
          siteId: string;
        };
      };
      responses: {
        200: components["responses"]["SiteUpdate"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SiteUpdate"];
    };
  };
  "/api/utility/savingTips": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetSavingTips"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/fuelSources": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetFuelSources"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/fuelUse": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          names?: string;
        };
      };
      responses: {
        200: components["responses"]["GetUsedIn"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/emissions": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          siteId?: string;
          year?: string;
        };
      };
      responses: {
        200: components["responses"]["GetEmissions"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/consumptions": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          siteId?: string;
          year?: string;
          month?: string;
        };
      };
      responses: {
        200: components["responses"]["GetConsumptions"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/utility/addEmission": {
    /** Add emision to utility. */
    post: {
      responses: {
        200: components["responses"]["AddFuelSourceEmission"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["AddFuelSourceEmission"];
    };
  };
  "/api/utility/addConsumption": {
    /** Add emision to utility. */
    post: {
      responses: {
        200: components["responses"]["AddFuelSourceConsumption"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["AddFuelSourceConsumption"];
    };
  };
  "/api/utility/addMonitoring": {
    /** Add emision to utility. */
    post: {
      responses: {
        200: components["responses"]["AddFuelSourceMonitoring"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["AddFuelSourceMonitoring"];
    };
  };
  "/api/utility/importUtility": {
    /** Import excel file. */
    post: {
      responses: {
        200: components["responses"]["UtilityFileImport"];
        400: components["schemas"]["GenericError"];
      };
      requestBody: components["requestBodies"]["UtilityFileImport"];
    };
  };
  "/api/utility/importLogs": {
    /** Import excel file. */
    post: {
      responses: {
        200: components["responses"]["LogFileImport"];
        400: components["schemas"]["GenericError"];
      };
      requestBody: components["requestBodies"]["LogFileImport"];
    };
  };
  "/api/dashboard/": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          year: string;
          fuelSourceId: string;
          order?: "asc" | "desc";
          siteId: string;
        };
      };
      responses: {
        200: components["responses"]["GetDashboardData"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/dashboard/reports": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          year: string;
          siteId: string;
          fuelSourceId: string;
        };
      };
      responses: {
        200: components["responses"]["GetDashboardReports"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/dashboard/carbonFootprint": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          year: string;
          siteId: string;
          order?: "asc" | "desc";
          fuelSourceId: string;
        };
      };
      responses: {
        200: components["responses"]["GetDashboardCarbonFootprint"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/dashboard/portfolio": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          year: string;
          month: string;
          fuelSourceId: string;
        };
      };
      responses: {
        200: components["responses"]["GetDashboardPortfolio"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/dashboard/energyWaste": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          year: string;
          month: string;
          fuelSourceId: string;
          order?: "asc" | "desc";
          siteId: string;
        };
      };
      responses: {
        200: components["responses"]["GetDashboardEnergyWaste"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetUser"];
        400: components["responses"]["GenericError"];
      };
    };
    /** Create a new user. */
    put: {
      responses: {
        200: components["responses"]["UpdateUser"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["UpdateUser"];
    };
  };
  "/api/business/energies": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetBusinessEnergy"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/sites": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          fsi?: string;
        };
      };
      responses: {
        200: components["responses"]["GetSites"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/foors": {
    /** Get dashboard data per date. */
    get: {
      parameters: {};
      responses: {
        200: components["responses"]["GetFloors"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/patterns": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          siteId?: string;
        };
      };
      responses: {
        200: components["responses"]["GetPatterns"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/logs": {
    /** Get dashboard data per date. */
    get: {
      parameters: {
        query: {
          siteId: string;
          year: string;
          month: string;
        };
      };
      responses: {
        200: components["responses"]["GetLogs"];
        400: components["responses"]["GenericError"];
      };
    };
  };
  "/api/business/saveEnergy": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SaveBusinessEnergy"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/savePattern": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SaveBusinessPattern"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessPattern"];
    };
  };
  "/api/business/addLog": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["AddLog"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/setTenants": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetTenants"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/setFloors": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetFloors"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SetFloors"];
    };
  };
  "/api/business/setReviews": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetReviews"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/setProgrammes": {
    /** Create a new user. */
    post: {
      responses: {
        200: components["responses"]["SetProgrammes"];
        400: components["responses"]["GenericError"];
      };
      requestBody: components["requestBodies"]["SaveBusinessEnergy"];
    };
  };
  "/api/business/importBusiness": {
    /** Import excel file. */
    post: {
      responses: {
        200: components["responses"]["FileImportBusiness"];
        400: components["schemas"]["GenericError"];
      };
      requestBody: components["requestBodies"]["FileImportBusiness"];
    };
  };
  "/api/business/importTenants": {
    /** Import excel file. */
    post: {
      responses: {
        200: components["responses"]["FileImportBusiness"];
        400: components["schemas"]["GenericError"];
      };
      requestBody: components["requestBodies"]["FileImportBusiness"];
    };
  };
  "/api/business/importPatterns": {
    /** Import excel file. */
    post: {
      responses: {
        200: components["responses"]["FileImportBusinessPatterns"];
        400: components["schemas"]["GenericError"];
      };
      requestBody: components["requestBodies"]["FileImportBusinessPatterns"];
    };
  };
  "/api/conversionUnit/": {
    /** Create a new site for a business. */
    get: {
      parameters: {
        query: {
          fuelSource?: ("L" | "m3")[];
        };
      };
      responses: {
        200: components["responses"]["GetConversionUnit"];
        400: components["responses"]["GenericError"];
      };
    };
  };
}

export interface components {
  schemas: {
    GenericError: {
      statusCode: number;
      message: string;
    };
    SuccessMessage: {
      success: boolean;
    };
    Site: {
      id?: number;
      name: string;
      type: string;
      address: string;
      postCode: string;
      town: string;
      population: number;
      size: number;
      workinghours: number;
      fullTimeEmployee?: boolean;
      countryId?: number;
      stateId?: number;
    };
    JWTToken: {
      jwt: string;
    };
    BusinessPattern: {
      startDate: string;
      endDate: string;
      temperature: number;
      daysOnYear: number;
      siteId: number;
      usedInId: number;
    };
    Programme: {
      question: string;
      siteId: number;
      usedInId: number;
      answers: string[];
    };
    Review: {
      question: string;
      siteId: number;
      answers: string[];
    };
    BusinessBrand: {
      name: string;
      rate: number;
      startTime: string;
      endTime: string;
      days: string[];
    };
    BusinessCost: {
      currencyCode: string;
      vat: number;
    };
    BusinessDistance: {
      meters: string;
    };
    BusinessFloor: {
      size: string;
      area: number;
      population: number;
    };
    SavingTip: {
      id: number;
      category: string;
      text: string;
      imageUrl?: string | null;
    };
    BusinessEnergy: {
      fuelSourceId: number;
      usedInId: number[];
      brands: components["schemas"]["BusinessBrand"][];
      meternumbers: components["schemas"]["BusinessDistance"][];
      cost: components["schemas"]["BusinessCost"];
    };
    Tenant: {
      siteId: number;
      usedInId: number;
      date: string;
      regularTenantAmount: number;
      irregularTenantAmount: number;
    };
    FuelSource: {
      source: string;
      colorCode: string;
      usedIn: string[];
    };
    EnergyLog: {
      siteId: number;
      usedInId: number;
      operation: string;
      comments: string;
      startDate: string;
      endDate: string;
    };
    FuelUse: {
      use: string;
    };
    RegisterBody: {
      businessName: string;
      businessType: string;
      businessService: string;
      buildingName: string;
      contactName: string;
      position: string;
      phoneNumber: string;
      email: string;
      countryId?: number;
      password?: string;
      stateId?: number;
      town?: string;
      postCode?: string;
      currencyCode?: string;
      address_1: string;
      subscriptionDate: string;
      floors?: components["schemas"]["BusinessFloor"][];
    };
    User: components["schemas"]["RegisterBody"] & {
      id: number;
      floors?: {
        size: string;
        area: number;
        population: number;
      }[];
      patterns?: components["schemas"]["BusinessPattern"][];
    };
    AddFuelSourceConsumptionBody: {
      date: string;
      consumption: number;
      totalCost: number;
      conversionFactor: number;
      fuelUnit: string;
      vat: number;
      siteId: number;
      fuelSourceId: number;
      usedInId: number[];
    };
    AddFuelSourceEmissionBody: {
      emissionFactor: number;
      conversionFactor: number;
      date: string;
      fuelUnit: string;
      siteId: number;
      fuelSourceId: number;
      usedInId: number[];
    };
    UtilityEmission: components["schemas"]["AddFuelSourceEmissionBody"] & {
      id: number;
    };
    UtilityConsumption: components["schemas"]["AddFuelSourceConsumptionBody"] &
      ({
        id: number;
        fuelSourceName: string;
      } & {
        conversionUnit: unknown;
      });
  };
  responses: {
    /** Error message */
    GenericError: {
      content: {
        "application/json": components["schemas"]["GenericError"];
      };
    };
    /** Success message */
    Register: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    Login: {
      content: {
        "application/json": components["schemas"]["JWTToken"];
      };
    };
    /** Success message */
    Site: {
      content: {
        "application/json": {
          id: number;
        };
      };
    };
    /** Success message */
    AddFuelSourceConsumption: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    UtilityFileImport: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetDashboardData: {
      content: {
        "application/json": {
          consumptions: {
            date: string;
            averageConsumption: number;
            averageCost: number;
            consumption: number;
            increasedConsumptionPercentage: number;
            increasedCostPercentage?: number;
          }[];
          energyTargets: {
            date: string;
            projectedEnergy: number;
            consumption: number;
            saving: number;
            siteId: number;
          }[];
          consumptionsDetails?: {
            date: string;
            fuelSourceName: string;
            incesedPercentage: number;
            consumption: number;
          }[];
        };
      };
    };
    /** Success message */
    UpdateUser: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetUser: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    /** Success message */
    SaveBusinessEnergy: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetSavingTips: {
      content: {
        "application/json": components["schemas"]["SavingTip"][];
      };
    };
    /** Success message */
    GetBusinessEnergy: {
      content: {
        "application/json": ({
          siteId: number;
        } & components["schemas"]["BusinessEnergy"])[];
      };
    };
    /** Success message */
    AddFuelSourceEmission: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    AddLog: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    SetTenants: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    SetReviews: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    SetProgrammes: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetSites: {
      content: {
        "application/json": components["schemas"]["Site"][];
      };
    };
    /** Success message */
    GetFuelSources: {
      content: {
        "application/json": (components["schemas"]["FuelSource"] & {
          id: number;
        })[];
      };
    };
    /** Success message */
    SetFloors: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetFloors: {
      content: {
        "application/json": components["schemas"]["BusinessFloor"][];
      };
    };
    /** Success message */
    GetEmissions: {
      content: {
        "application/json": components["schemas"]["UtilityEmission"][];
      };
    };
    /** Success message */
    GetConsumptions: {
      content: {
        "application/json": components["schemas"]["UtilityConsumption"][];
      };
    };
    /** Success message */
    DeleteSite: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetSiteDetails: {
      content: {
        "application/json": {
          programmes: components["schemas"]["Programme"][];
          reviews: components["schemas"]["Review"][];
          tenants: components["schemas"]["Tenant"][];
          logs: components["schemas"]["EnergyLog"][];
          energies: components["schemas"]["BusinessEnergy"][];
        };
      };
    };
    /** Success message */
    SiteUpdate: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    SaveBusinessPattern: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    LogFileImport: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetUsedIn: {
      content: {
        "application/json": components["schemas"]["FuelUse"][];
      };
    };
    /** Success message */
    GetCountries: {
      content: {
        "application/json": {
          id: number;
          name: string;
        }[];
      };
    };
    /** Success message */
    GetStates: {
      content: {
        "application/json": {
          id: number;
          name: string;
        }[];
      };
    };
    /** Success message */
    GetPatterns: {
      content: {
        "application/json": components["schemas"]["BusinessPattern"][];
      };
    };
    /** Success message */
    FileImportBusiness: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    FileImportBusinessTenants: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    FileImportBusinessPatterns: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetLogs: {
      content: {
        "application/json": {
          logs: components["schemas"]["EnergyLog"][];
          tenants: components["schemas"]["Tenant"][];
        };
      };
    };
    /** Success message */
    GetDashboardReports: {
      content: {
        "application/json": {
          energyTargets: {
            date: string;
            projectedEnergy: number;
            consumption: number;
          }[];
          carbonEmissions: {
            date: string;
            carbonEmission: number;
            carbonTarget: number;
          }[];
          reports: {
            id: number;
          }[];
        };
      };
    };
    /** Success message */
    GetDashboardCarbonFootprint: {
      content: {
        "application/json": {
          carbonEmissions: {
            date: string;
            carbonEmission: number;
            carbonTarget: number;
          }[];
        };
      };
    };
    /** Success message */
    GetDashboardPortfolio: {
      content: {
        "application/json": {
          carbonEmissions: {
            date: string;
            carbonEmission: number;
            carbonTarget: number;
          }[];
        };
      };
    };
    /** Success message */
    GetDashboardEnergyWaste: {
      content: {
        "application/json": {
          energyTargets: {
            date: string;
            projectedEnergy: number;
            consumption: number;
            saving: number;
            siteId: number;
          }[];
        };
      };
    };
    /** Success message */
    SetSiteConversionUnit: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
    /** Success message */
    GetConversionUnit: {
      content: {
        "application/json": {
          value: number;
          unit: "L" | "m3" | "kWh";
        }[];
      };
    };
    /** Success message */
    AddFuelSourceMonitoring: {
      content: {
        "application/json": components["schemas"]["SuccessMessage"];
      };
    };
  };
  parameters: {
    GetSiteDetails: number;
  };
  requestBodies: {
    Register: {
      content: {
        "application/json": components["schemas"]["RegisterBody"];
      };
    };
    Login: {
      content: {
        "application/json": {
          email: string;
          password: string;
        };
      };
    };
    Site: {
      content: {
        "application/json": components["schemas"]["Site"];
      };
    };
    AddFuelSourceConsumption: {
      content: {
        "application/json": components["schemas"]["AddFuelSourceConsumptionBody"][];
      };
    };
    UtilityFileImport: {
      content: {
        "multipart/form-data": {
          excel?: string;
        };
        "application/json": string;
      };
    };
    UpdateUser: {
      content: {
        "application/json": components["schemas"]["RegisterBody"];
      };
    };
    SaveBusinessEnergy: {
      content: {
        "application/json": {
          siteId: number;
          records: components["schemas"]["BusinessEnergy"][];
        };
      };
    };
    AddFuelSourceEmission: {
      content: {
        "application/json": components["schemas"]["AddFuelSourceEmissionBody"][];
      };
    };
    AddLog: {
      content: {
        "application/json": components["schemas"]["EnergyLog"];
      };
    };
    SetTenants: {
      content: {
        "application/json": components["schemas"]["Tenant"][];
      };
    };
    SetReviews: {
      content: {
        "application/json": components["schemas"]["Review"][];
      };
    };
    SetProgrammes: {
      content: {
        "application/json": components["schemas"]["Programme"][];
      };
    };
    SetFloors: {
      content: {
        "application/json": components["schemas"]["BusinessFloor"][];
      };
    };
    DeleteSite: {
      content: {
        "application/json": {
          id: number;
        };
      };
    };
    SiteUpdate: {
      content: {
        "application/json": components["schemas"]["Site"];
      };
    };
    SaveBusinessPattern: {
      content: {
        "application/json": components["schemas"]["BusinessPattern"][];
      };
    };
    LogFileImport: {
      content: {
        "multipart/form-data": {
          excel?: string;
        };
        "application/json": string;
      };
    };
    FileImportBusiness: {
      content: {
        "multipart/form-data": {
          excel?: string;
        };
        "application/json": string;
      };
    };
    FileImportBusinessTenants: {
      content: {
        "multipart/form-data": {
          excel?: string;
        };
        "application/json": string;
      };
    };
    FileImportBusinessPatterns: {
      content: {
        "multipart/form-data": {
          excel?: string;
        };
        "application/json": string;
      };
    };
    SetSiteConversionUnit: {
      content: {
        "application/json": {
          unitValue: number;
          unitType: "L" | "m3" | "kWh";
        }[];
      };
    };
    AddFuelSourceMonitoring: {
      content: {
        "application/json": {
          carbon: number;
          conversionFactor: number;
          energy: number;
          date: string;
          fuelUnit: string;
          siteId: number;
          fuelSourceId: number;
          usedInId: number[];
        }[];
      };
    };
  };
}

export interface operations {}

export interface external {}
