export default {
  oldHdd: [
    {
      date: new Date(2023, 0, 1),
      value: 140,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 1, 1),
      value: 130,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 2, 1),
      value: 100,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 3, 1),
      value: 90,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 4, 1),
      value: 80,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 5, 1),
      value: 70,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 6, 1),
      value: 60,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 7, 1),
      value: 50,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 8, 1),
      value: 90,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 9, 1),
      value: 100,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 10, 1),
      value: 120,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2023, 11, 1),
      value: 140,
      siteId: 19,
      kind: 'HDD' as const,
    },

    {
      date: new Date(2023, 0, 1),
      value: 20,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 1, 1),
      value: 20,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 2, 1),
      value: 100,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 3, 1),
      value: 120,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 4, 1),
      value: 130,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 5, 1),
      value: 140,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 6, 1),
      value: 150,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 7, 1),
      value: 130,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 8, 1),
      value: 120,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 9, 1),
      value: 50,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 10, 1),
      value: 50,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2023, 11, 1),
      value: 20,
      siteId: 19,
      kind: 'CDD' as const,
    },
  ],

  nextHdd: [
    {
      date: new Date(2024, 0, 1),
      value: 10,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 1, 1),
      value: 6,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 2, 1),
      value: 20,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 3, 1),
      value: 30,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 4, 1),
      value: 15,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 5, 1),
      value: 26,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 6, 1),
      value: 28,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 7, 1),
      value: 29,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 8, 1),
      value: 26,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 9, 1),
      value: 32,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 10, 1),
      value: 21,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 11, 1),
      value: 20,
      siteId: 19,
      kind: 'HDD' as const,
    },
    {
      date: new Date(2024, 0, 1),
      value: 5,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 1, 1),
      value: 7,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 2, 1),
      value: 8,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 3, 1),
      value: 5,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 4, 1),
      value: 6,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 5, 1),
      value: 7,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 6, 1),
      value: 8,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 7, 1),
      value: 11,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 8, 1),
      value: 12,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 9, 1),
      value: 13,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 10, 1),
      value: 8,
      siteId: 19,
      kind: 'CDD' as const,
    },
    {
      date: new Date(2024, 11, 1),
      value: 10,
      siteId: 19,
      kind: 'CDD' as const,
    },
  ],
};
