server {
        listen 80;
        listen [::]:80;
        error_log /var/log/nginx/error_log_energypad_80;

        server_name app.energiepad.com www.app.energiepad.com;

        add_header Strict-Transport-Security "max-age=0";

        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl ;
        listen [::]:443 ssl ;
        error_log /var/log/nginx/error_log_energypad;

        add_header Strict-Transport-Security "max-age=0";
        ssl_certificate /etc/ssl/energiepad/crt.crt;
        ssl_certificate_key /etc/ssl/energiepad/key.key;

        server_name app.energiepad.com www.app.energiepad.com;

        root /home/zakajia/Energiepad/energiepadui/build;
        index index.html;

        location / {
                proxy_pass http://localhost:3000;
        }

        location /api {
                proxy_pass http://localhost:5000;
        }

        location /assets {
                proxy_pass http://localhost:5000;
        }

}
