server {
        listen 80;
        listen [::]:80;
        error_log /var/log/nginx/error_log_energypad_80;

        server_name app.energiepad.com www.app.energiepad.com;

        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl ;
        listen [::]:443 ssl ;
        error_log /var/log/nginx/error_log_energypad;

        ssl_certificate /etc/ssl/energiepad/crt.crt;
        ssl_certificate_key /etc/ssl/energiepad/key.key;

        server_name app.energiepad.com www.app.energiepad.com;

        location / {
                proxy_pass http://front:3000;
        }

        location /api {
                proxy_pass http://api:5000;
        }

        location /assets {
                proxy_pass http://api:5000;
        }

}
