import dashboard from '../../dashboard.service';

export const buildFakeConsumption = (p: {
  id: number;
  date: string;
  consumption: number;
  siteId: number;
  fuelSourceId: number;
  usedInId?: number;
  totalCost?: number;
}) => {
  return {
    id: p.id,
    date: p.date,
    consumption: p.consumption,
    vat: 20,
    conversionFactor: 10,
    totalCost: p.totalCost || 10,
    fuelUnit: 'm3',
    siteId: p.siteId,
    fuelSourceId: p.fuelSourceId,
    usedInId: p.usedInId || 2,
    usedIn: '',
    fuelSourceName: '',
    siteName: '',
    conversionUnit: 1,
    population: 0,
    workingHours: 0
  };
};

test('single fuel test', async () => {
  const params = {
    consumptions: [
      {
        id: 0,
        consumption: 99,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2020-12-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 99,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-01-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 3,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 160,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-01-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 180,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-02-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 190,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-03-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 150,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-04-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 280,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-05-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 220,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-06-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 250,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-07-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 300,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-08-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 250,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-09-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 250,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-10-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 200,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-11-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 200,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2021-12-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
    ],
    hdd: [
      { value: 2166.5, date: new Date(2021, 0, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1904.3, date: new Date(2021, 1, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1996.7, date: new Date(2021, 2, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1799.9, date: new Date(2021, 3, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1734.6, date: new Date(2021, 4, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1546.1, date: new Date(2021, 5, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1435.9, date: new Date(2021, 6, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1441, date: new Date(2021, 7, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1526.8, date: new Date(2021, 8, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1723, date: new Date(2021, 9, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1792.4, date: new Date(2021, 10, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1976.6, date: new Date(2021, 11, 1), siteId: 1, kind: 'HDD' as const },
    ],
    nextConsumptions: [
      {
        id: 0,
        consumption: 190,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-01-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 210,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-02-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 220,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-03-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 190,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-04-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 370,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-05-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 290,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-06-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 280,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-07-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 350,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-08-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 290,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-09-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 210,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-10-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 280,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-11-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
      {
        id: 0,
        consumption: 200,
        fuelSourceName: 'a',
        siteName: 'a',
        conversionUnit: 1,
        date: '2022-12-01',
        totalCost: 0,
        conversionFactor: 0,
        fuelUnit: 'a',
        vat: 0,
        fuelSourceId: 1,
        usedInId: 1,
        usedIn: '',
        siteId: 1,
        population: 0,
        workingHours: 0
      },
    ],
    nextHdd: [
      { value: 2008.2, date: new Date(2022, 0, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1870.9, date: new Date(2022, 1, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1991.9, date: new Date(2022, 2, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1785, date: new Date(2022, 3, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1726, date: new Date(2022, 4, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1532.2, date: new Date(2022, 5, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1405, date: new Date(2022, 6, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1457.1, date: new Date(2022, 7, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1455.6, date: new Date(2022, 8, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1668.7, date: new Date(2022, 9, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1892, date: new Date(2022, 10, 1), siteId: 1, kind: 'HDD' as const },
      { value: 1989.8, date: new Date(2022, 11, 1), siteId: 1, kind: 'HDD' as const },
    ],
    year: 2022,
  };

  const result = dashboard.wasteForSinglefuelFunction(params);
  expect(result.length).toBe(12);
  expect(result[0].waste).toBe(-8.9967);
  expect(result[1].waste).toBe(-8.412);
  expect(result[2].waste).toBe(-36.5529);
  expect(result[3].waste).toBe(24.4665);
  expect(result[4].waste).toBe(-146.6878);
  expect(result[5].waste).toBe(-37.6324);
  expect(result[6].waste).toBe(-8.5619);
  expect(result[7].waste).toBe(-86.373);
  expect(result[8].waste).toBe(-26.1481);
  expect(result[9].waste).toBe(21.9028);
  expect(result[10].waste).toBe(-81.5754);
  expect(result[11].waste).toBe(-16.2381);
});

test('multiple heating cooling and lighting', async () => {
  const params: Parameters<typeof dashboard.wasteForPowerAndLightingAndCooling>[0] = {
    consumptions: [
      buildFakeConsumption({
        id: 1,
        date: '2013-01-01',
        consumption: 45,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2013-02-01',
        consumption: 44,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2013-03-01',
        consumption: 50,
        siteId: 2,
        fuelSourceId: 1,
      }),
      buildFakeConsumption({
        id: 1,
        date: '2013-04-01',
        consumption: 43,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2013-05-01',
        consumption: 45,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2013-06-01',
        consumption: 44,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2013-07-01',
        consumption: 40,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2013-08-01',
        consumption: 43,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2013-09-01',
        consumption: 39,
        siteId: 2,
        fuelSourceId: 1,
      }),
      buildFakeConsumption({
        id: 1,
        date: '2013-10-01',
        consumption: 40,
        siteId: 2,
        fuelSourceId: 1,
      }),
      buildFakeConsumption({
        id: 1,
        date: '2013-11-01',
        consumption: 45,
        siteId: 2,
        fuelSourceId: 1,
      }),
      buildFakeConsumption({
        id: 1,
        date: '2013-12-01',
        consumption: 40,
        siteId: 2,
        fuelSourceId: 1,
      }),
    ],

    coolingDegrees: [
      { value: 4, date: new Date(2013, 0, 1), siteId: 2, kind: 'CDD' as const },
      { value: 5, date: new Date(2013, 1, 1), siteId: 2, kind: 'CDD' as const },
      { value: 6, date: new Date(2013, 2, 1), siteId: 2, kind: 'CDD' as const },
      { value: 6, date: new Date(2013, 3, 1), siteId: 2, kind: 'CDD' as const },
      { value: 5, date: new Date(2013, 4, 1), siteId: 2, kind: 'CDD' as const },
      { value: 3, date: new Date(2013, 5, 1), siteId: 2, kind: 'CDD' as const },
      { value: 4, date: new Date(2013, 6, 1), siteId: 2, kind: 'CDD' as const },
      { value: 5, date: new Date(2013, 7, 1), siteId: 2, kind: 'CDD' as const },
      { value: 7, date: new Date(2013, 8, 1), siteId: 2, kind: 'CDD' as const },
      { value: 8, date: new Date(2013, 9, 1), siteId: 2, kind: 'CDD' as const },
      { value: 9, date: new Date(2013, 10, 1), siteId: 2, kind: 'CDD' as const },
      { value: 10, date: new Date(2013, 11, 1), siteId: 2, kind: 'CDD' as const },
    ],
    heatingDegrees: [
      { value: 8, date: new Date(2013, 0, 1), siteId: 2, kind: 'HDD' as const },
      { value: 7, date: new Date(2013, 1, 1), siteId: 2, kind: 'HDD' as const },
      { value: 8, date: new Date(2013, 2, 1), siteId: 2, kind: 'HDD' as const },
      { value: 6, date: new Date(2013, 3, 1), siteId: 2, kind: 'HDD' as const },
      { value: 9, date: new Date(2013, 4, 1), siteId: 2, kind: 'HDD' as const },
      { value: 8, date: new Date(2013, 5, 1), siteId: 2, kind: 'HDD' as const },
      { value: 9, date: new Date(2013, 6, 1), siteId: 2, kind: 'HDD' as const },
      { value: 6, date: new Date(2013, 7, 1), siteId: 2, kind: 'HDD' as const },
      { value: 8, date: new Date(2013, 8, 1), siteId: 2, kind: 'HDD' as const },
      { value: 10, date: new Date(2013, 9, 1), siteId: 2, kind: 'HDD' as const },
      { value: 12, date: new Date(2013, 10, 1), siteId: 2, kind: 'HDD' as const },
      { value: 14, date: new Date(2013, 11, 1), siteId: 2, kind: 'HDD' as const },
    ],
    nextConsumptions: [
      buildFakeConsumption({
        id: 1,
        date: '2014-01-01',
        consumption: 48,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2014-02-01',
        consumption: 42,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2014-03-01',
        consumption: 54,
        siteId: 2,
        fuelSourceId: 1,
      }),
      buildFakeConsumption({
        id: 1,
        date: '2014-04-01',
        consumption: 70,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2014-05-01',
        consumption: 68,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2014-06-01',
        consumption: 89,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2014-07-01',
        consumption: 65,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2014-08-01',
        consumption: 78,
        siteId: 2,
        fuelSourceId: 1,
      }),

      buildFakeConsumption({
        id: 1,
        date: '2014-09-01',
        consumption: 57,
        siteId: 2,
        fuelSourceId: 1,
      }),
      buildFakeConsumption({
        id: 1,
        date: '2014-10-01',
        consumption: 76,
        siteId: 2,
        fuelSourceId: 1,
      }),
      buildFakeConsumption({
        id: 1,
        date: '2014-11-01',
        consumption: 68,
        siteId: 2,
        fuelSourceId: 1,
      }),
      buildFakeConsumption({
        id: 1,
        date: '2014-12-01',
        consumption: 65,
        siteId: 2,
        fuelSourceId: 1,
      }),
    ],
    nextCoolingDegrees: [
      { value: 5, date: new Date(2014, 0, 1), siteId: 2, kind: 'CDD' as const },
      { value: 7, date: new Date(2014, 1, 1), siteId: 2, kind: 'CDD' as const },
      { value: 8, date: new Date(2014, 2, 1), siteId: 2, kind: 'CDD' as const },
      { value: 5, date: new Date(2014, 3, 1), siteId: 2, kind: 'CDD' as const },
      { value: 6, date: new Date(2014, 4, 1), siteId: 2, kind: 'CDD' as const },
      { value: 7, date: new Date(2014, 5, 1), siteId: 2, kind: 'CDD' as const },
      { value: 8, date: new Date(2014, 6, 1), siteId: 2, kind: 'CDD' as const },
      { value: 11, date: new Date(2014, 7, 1), siteId: 2, kind: 'CDD' as const },
      { value: 12, date: new Date(2014, 8, 1), siteId: 2, kind: 'CDD' as const },
      { value: 13, date: new Date(2014, 9, 1), siteId: 2, kind: 'CDD' as const },
      { value: 8, date: new Date(2014, 10, 1), siteId: 2, kind: 'CDD' as const },
      { value: 10, date: new Date(2014, 11, 1), siteId: 2, kind: 'CDD' as const },
    ],
    nextHeatingDegrees: [
      { value: 10, date: new Date(2014, 0, 1), siteId: 2, kind: 'HDD' as const },
      { value: 6, date: new Date(2014, 1, 1), siteId: 2, kind: 'HDD' as const },
      { value: 20, date: new Date(2014, 2, 1), siteId: 2, kind: 'HDD' as const },
      { value: 30, date: new Date(2014, 3, 1), siteId: 2, kind: 'HDD' as const },
      { value: 15, date: new Date(2014, 4, 1), siteId: 2, kind: 'HDD' as const },
      { value: 26, date: new Date(2014, 5, 1), siteId: 2, kind: 'HDD' as const },
      { value: 28, date: new Date(2014, 6, 1), siteId: 2, kind: 'HDD' as const },
      { value: 29, date: new Date(2014, 7, 1), siteId: 2, kind: 'HDD' as const },
      { value: 26, date: new Date(2014, 8, 1), siteId: 2, kind: 'HDD' as const },
      { value: 32, date: new Date(2014, 9, 1), siteId: 2, kind: 'HDD' as const },
      { value: 21, date: new Date(2014, 10, 1), siteId: 2, kind: 'HDD' as const },
      { value: 20, date: new Date(2014, 11, 1), siteId: 2, kind: 'HDD' as const },
    ],
  };

  const results = dashboard.wasteForPowerAndLightingAndCooling(params);

  expect(results.length).toBe(12);
  expect(results[0].waste).toBe(-50.74336283);
  expect(results[1].waste).toBe(-44.84955752);
  expect(results[2].waste).toBe(-58.88495575);
  expect(results[3].waste).toBe(-75.22123894);
});
