// Catalogue and illustrations restored from the legacy EnergySavingTips seed.
export const energyTips = [
  {
    id: 1,
    category: 'Cooling',
    text: 'Raise energy awareness more often to users. This can be via e-mail, face-to-face, webinars or workshops.',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 1.jpg',
  },
  {
    id: 2,
    category: 'Cooling',
    text: 'Turn off unused Air Conditioning Systems',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 2.jpg',
  },
  {
    id: 3,
    category: 'Cooling',
    text: 'Match air conditioning operating times with building operating times',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 3.jpg',
  },
  {
    id: 4,
    category: 'Cooling',
    text: 'Set the time for your cooling systems to come on a little late than normally to ensure your building reduces power whilst not sacrificing thermal comfort',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 4.jpg',
  },
  {
    id: 5,
    category: 'Cooling',
    text: 'Clean Vents regularly to reduce colling energy',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 5.jpg',
  },
  {
    id: 6,
    category: 'Cooling',
    text: 'Unplug unused servers to reduce colling needs',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 6.jpg',
  },
  {
    id: 7,
    category: 'Cooling',
    text: 'Check that the HVAC housing unit is not leaking',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 7.jpg',
  },
  {
    id: 8,
    category: 'Cooling',
    text: 'Lower the speed of fans to reduce cooling energy',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 8.jpg',
  },
  {
    id: 9,
    category: 'Cooling',
    text: 'Close all windows during cooling to prevent air infiltration',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 9.jpg',
  },
  {
    id: 10,
    category: 'Cooling',
    text: 'Shut doors properly to prevent heat infiltration',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 10.jpg',
  },
  {
    id: 11,
    category: 'Cooling',
    text: 'Wherever possible, open windows when air conditioning system is off to access free cooling',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 11.jpg',
  },
  {
    id: 12,
    category: 'Cooling',
    text: 'Ensure your air conditioning system is not on while windows are left open',
    imageUrl: '/assets/energyTipsImages/cooling/Cooling Energy_Artboard 12.jpg',
  },
  {
    id: 13,
    category: 'Cooling',
    text: 'Increase cooling set points by 1 degree if possible',
    imageUrl: null,
  },
  {
    id: 14,
    category: 'Heating',
    text: 'Raise energy awareness more often to users. This can be via e-mail, face-to-face, webinars or workshops.',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 1.jpg',
  },
  {
    id: 15,
    category: 'Heating',
    text: 'Turn off unused radiators',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 2.jpg',
  },
  {
    id: 16,
    category: 'Heating',
    text: 'Set the time for your heating to come on a little late than normally to ensure your building reduces heating energy whilst not sacrificing thermal comfort',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 3.jpg',
  },
  {
    id: 17,
    category: 'Heating',
    text: 'Service your heating systems regularly to increase its operational efficiency to save heating',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 4.jpg',
  },
  {
    id: 18,
    category: 'Heating',
    text: 'Close all windows during heating to prevent air infiltration',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 5.jpg',
  },
  {
    id: 19,
    category: 'Heating',
    text: 'Shut doors during heating properly to prevent air infiltration',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 6.jpg',
  },
  {
    id: 20,
    category: 'Heating',
    text: 'Draft proof doors',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 7.jpg',
  },
  {
    id: 21,
    category: 'Heating',
    text: 'Check that insulation on building fabrics are in good condition',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 8.jpg',
  },
  {
    id: 22,
    category: 'Heating',
    text: 'Check that there are no hot water leaks',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 9.jpg',
  },
  {
    id: 23,
    category: 'Heating',
    text: 'Use water efficiently and cut back on hot water use',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 10.jpg',
  },
  {
    id: 24,
    category: 'Heating',
    text: 'Check that radiator are free of obstructions at all time',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 11.jpg',
  },
  {
    id: 25,
    category: 'Heating',
    text: 'Reduce heating setpoint by 1 degree if possible',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 12.jpg',
  },
  {
    id: 26,
    category: 'Heating',
    text: 'Match heating supply to the building with operating times',
    imageUrl: '/assets/energyTipsImages/heating/Heating Energy_Artboard 13.jpg',
  },
  {
    id: 27,
    category: 'Power',
    text: 'Raise energy awareness more often to users. This can be via e-mail, face-to-face, webinars or workshops.',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 1.jpg',
  },
  {
    id: 28,
    category: 'Power',
    text: 'Turn off unused lights off',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 2.jpg',
  },
  {
    id: 29,
    category: 'Power',
    text: 'Walk through to turn off lights',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 3.jpg',
  },
  {
    id: 30,
    category: 'Power',
    text: 'Check to see sensors/lighting control systems are working properly in relation to building use',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 4.jpg',
  },
  {
    id: 31,
    category: 'Power',
    text: 'Sets your lighting sensors to turn off lighting a little earlier than normally if possible',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 5.jpg',
  },
  {
    id: 32,
    category: 'Power',
    text: 'Dim the brightness of your devices and lights, if possible, to reduce electricity use',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 6.jpg',
  },
  {
    id: 33,
    category: 'Power',
    text: 'Unplug unused servers',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 7.jpg',
  },
  {
    id: 34,
    category: 'Power',
    text: 'Check that to there are no water leaks',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 8.jpg',
  },
  {
    id: 35,
    category: 'Power',
    text: 'Reduce office use and intensive activities during peak times',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 9.jpg',
  },
  {
    id: 36,
    category: 'Power',
    text: 'Discourage use of personal phones at work to reduce recharges and save electricity',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 10.jpg',
  },
  {
    id: 37,
    category: 'Power',
    text: 'Make sure your security lights off at the earliest point when day light set in',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 11.jpg',
  },
  {
    id: 38,
    category: 'Power',
    text: 'Make sure your security lights are switched off during working hours',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 12.jpg',
  },
  {
    id: 39,
    category: 'Power',
    text: 'Shut computers off completely when not in use',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 13.jpg',
  },
  {
    id: 40,
    category: 'Power',
    text: 'Switch off lights or reduce the number of lights on when daylighting can be harvested',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 14.jpg',
  },
  {
    id: 41,
    category: 'Power',
    text: 'Clean lighting fixtures to improve light reflectance',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 15.jpg',
  },
  {
    id: 42,
    category: 'Power',
    text: 'Clean device screenplays',
    imageUrl: '/assets/energyTipsImages/powerAndLighting/Power and Lighting Energy_Artboard 16.jpg',
  },
] as const;
